### ISSUE TITLE
Some gold standard phenotype nodes are not present in the merged KG

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#18]
As per Guojing Cong:

> I noticed some of the golden standard ids are not in the graph,  for example, 'HP:0025668'

I had expected all nodes with these gold standard phenotype vs. phenotype equivalency relationships to be present in the KG, but this may not be the case. Should check to see how many really are present in the graph or not.

`monarch.owl` does not import the entirety of HP or MP (see https://github.com/monarch-initiative/monarch-ontology/blob/master/monarch.owl) but it does import http://purl.obolibrary.org/obo/upheno/metazoa.owl and http://purl.obolibrary.org/obo/upheno/hp-mp/mp_hp-align-equiv.owl .

**Comment by justaddcoffee** [comment]
Possibly some of these nodes are newer HPO terms not present in our KG yet. For example, HP:0025668 doesn't seem to be on at least [one HPO browser](https://mseqdr.org/search_phenotype.php?hponame=HP:0025668&dbsource=genomic)

**Comment by caufieldjh** [comment]
I found six HPO terms present in the gold standard but not in the graph nodes:
```
HP:0025668
HP:0025675
HP:0025692
HP:0025707
HP:0025713
HP:0025722
```

and the same for MP:
```
MP:0021107
MP:0031312
MP:0031313
MP:0031314
MP:0031315
MP:0031316
MP:0031343
MP:0031344
MP:0031345
MP:0031347
MP:0031349
MP:0031350
MP:0031358
```

**Comment by matentzn** [comment]
Ok thanks! You are not using upheno2?

**Comment by caufieldjh** [comment]
This is an old issue but all of the above CURIEs are not present as of KG build 20241203.
