### ISSUE TITLE
rename project from kg-ontoml to kg-phenio

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-phenio#32]
Per convo with Chris, we maybe should rename this KG project to be something more accurate, like kg-phenio or kg-monarch-owl.

OntoML aspires to learn on ontologies generally - this KG project is one that integrates data specifically from the Monarch graph, starting with the ontologies present in Monarch

If we are going to rename, we probably should do it now before we publish KG-Hub

**Comment by caufieldjh** [comment]
Sounds good to me! Would prefer KG-PHENIO over a name tying it to Monarch

**Comment by matentzn** [comment]
agree with not adding Monarch in the name. kg-phenio sounds good to me as well!

**Comment by caufieldjh** [comment]
Name is changed.
