### ISSUE TITLE
Broken links for artifacts in kg-phenio KG-hub

### ISSUE THREAD

**Issue by justaddcoffee** [Knowledge-Graph-Hub/kg-phenio#33]
Links to download artifacts in the kg-phenio directory of KG-Hub
https://kg-hub.berkeleybop.io/kg-phenio/index.html

Are broken, because they are pointing to the kg-ontoml artifacts (which are 404).

For example:
https://kg-hub.berkeleybop.io/kg-ontoml/20220504/KG-OntoML.tar.gz

I think the fix is to update existing `index.html` files to point to the new kg-phenio URLs. For example the broken link above should point to:
https://kg-hub.berkeleybop.io/kg-phenio/20220504/KG-OntoML.tar.gz

**Comment by caufieldjh** [comment]
Aha, you caught this just before I fixed it ☺

These should all be fixed now, e.g. see https://kg-hub.berkeleybop.io/kg-phenio/20220504/

**Comment by justaddcoffee** [comment]
These still seem broken, can you confirm? For example, on [this page](https://kg-hub.berkeleybop.io/kg-phenio/20220504/), click on [KG-OntoML.tar.gz](https://kg-hub.berkeleybop.io/kg-ontoml/20220504/KG-OntoML.tar.gz)

**Comment by caufieldjh** [comment]
Looks correct on my end -
![image](https://user-images.githubusercontent.com/7987729/167204345-282d1e1a-505b-42a4-84fd-b581458773d9.png)
Try a cache refresh?

**Comment by justaddcoffee** [comment]
Thanks Harry - I think cloudfront was still serving me an old cached version. Works on my end now, thanks!
