### ISSUE TITLE
More ZFA nodes

### ISSUE THREAD

**Issue by kevinschaper** [Knowledge-Graph-Hub/kg-phenio#57]
I have lots of ZFIN gene to ZFA expression edges that I want to support, but it looks like there are only a handful of ZFA nodes that are making it in. 

(Does that sound ok / make sense @matentzn?)

**Comment by matentzn** [comment]
Sorry I didn't read correctly. I meant: for which species do we ingest gene expression data? @caufieldjh phenio ODK need at least wbbt zfa and xao imports, as well as all (!) related bridges from Uberon.

**Comment by caufieldjh** [comment]
I see many more (~5945) ZFA nodes in KG build 20241203.
