### ISSUE TITLE
Include EMAPA in kg-phenio

### ISSUE THREAD

**Issue by kevinschaper** [Knowledge-Graph-Hub/kg-phenio#63]
Supporting Alliance gene expression in Monarch KG requires that we include the EMAPA ontology in Phenio.

https://obofoundry.org/ontology/emapa.html

(I'm not sure if this is a KG phenio issue or a direct phenio issue, but we'll start here)

**Comment by matentzn** [comment]
@kevinschaper best use https://github.com/monarch-initiative/phenio/issues in the future, but I agree, we can add species specific anatomy ontologies as they become relevant.

@caufieldjh when you add this, you need to remember to add at least the emapa to uberon and emapa to cl bridge files as well.

**Comment by caufieldjh** [comment]
No worries - can't transfer this issue as PHENIO is in a different org, but I'll open a ticket there so I remember to add this.

**Comment by caufieldjh** [comment]
Closing as completed.
