### ISSUE TITLE
Include more Biolink categories

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#75]
As of build [20220930](https://kg-hub.berkeleybop.io/kg-phenio/20220930/ ), the graph includes expected Biolink categories for the following namespaces:
```
CHEBI
CL
FlyBase
GO
HGNC
HP
MONDO
NCBIGene
NCBITaxon
OBO
PR
RO
SO
UBERON
```

These namespaces are assigned OntologyClass instead:
```
APO
BFO
BSPO
BTO
CARO
CHR
CIO
CLO
DATA
DDANAT
DDPHENO
DOID
ECO
ENVO
FAO
FBbt
FBcv
FBdv
FMA
FOODON
FYPO
FlyBase
GENO
GO
IAO
IDO
MA
MF
MFOMD
MI
MOD
MP
MPATH
NBO
NCIT
OBA
OBAN
OBI
OBO
OGMS
OIO
OMIM
PATO
PCO
PLANA
PO
PW
RO
RXCUI
SEPIO
SIO
STATO
UPHENO
WBPhenotype
WBbt
WD_Entity
WD_Prop
XAO
XCO
YPO
ZFA
ZFS
ZP
biolink
dc
dcat
dcterms
dctypes
faldo
foaf
owl
pav
rdf
rdfs
skos
```

Some categories may be modified by KGX though they're included in phenio.owl now. Additional category assignments should ideally be made during phenio assembly but could also be made here through ID remapping (i.e., at the same time as node normalization).

**Comment by kevinschaper** [comment]
Here's my short list for a next round of categories: 

```
FBbt:
FYPO:
GO:
MP:
MPATH:
OMIM:
WBPhenotype:
WBbt:
ZFA:
ZP:
```

I think also EMAPA, once it's in.

**Comment by caufieldjh** [comment]
Since the mappings are pulled directly from https://github.com/biolink/biolink-model, they should correspond to https://github.com/biolink/biolink-model/blob/master/prefix-map/biolink-model-prefix-map.json

**Comment by caufieldjh** [comment]
The CURIE prefixes themselves are defined under `prefixes` in the Biolink yaml: https://github.com/biolink/biolink-model/blob/master/biolink-model.yaml

**Comment by caufieldjh** [comment]
But then the ontology class to category is all under `id_prefixes` for each category in the model

**Comment by matentzn** [comment]
All of the ones @kevinschaper mentioned should have been added by this round.. They are all in biolink model! Maybe it has to do with https://github.com/monarch-initiative/phenio/edit/main/src/sparql/bl-categories.ru and the way narrow match is done?

**Comment by caufieldjh** [comment]
The match covers `skos:exactMatch` and `skos:narrowMatch` but not `skos:relatedMatch`, so that's certainly possible. Some namespaces, like `http://purl.obolibrary.org/obo/UPHENO_`, are very clearly defined in BL so it's not as clear why those aren't getting matched:

(`biolink-model.owl.ttl`)
```
biolink:PhenotypicFeature a owl:Class ;
    rdfs:label "phenotypic feature" ;
    rdfs:subClassOf biolink:DiseaseOrPhenotypicFeature ;
    skos:altLabel "endophenotype",
        "phenotype",
        "sign",
        "symptom",
        "trait" ;
    skos:broadMatch <http://purl.obolibrary.org/obo/BFO_0000019>,
        <http://purl.obolibrary.org/obo/PATO_0000001> ;
    skos:definition "A combination of entity and quality that makes up a phenotyping statement. An observable characteristic of an  individual resulting from the interaction of its genotype with its molecular and physical environment." ;
    skos:exactMatch MESH:D010641,
        <http://identifiers.org/umls/C4021819>,
        <http://purl.obolibrary.org/obo/NCIT_C16977>,
        <http://purl.obolibrary.org/obo/UPHENO_0001001>,
        SIO:010056,
        SNOMEDCT:8116006,
        WIKIDATA:Q104053 ;
    skos:narrowMatch STY:T184,
        <http://purl.obolibrary.org/obo/APO_0000017>,
        <http://purl.obolibrary.org/obo/FBcv_0001347>,
        FYPO:0000001,
        <http://purl.obolibrary.org/obo/HP_0000118>,
        <http://purl.obolibrary.org/obo/MP_0000001>,
        <http://purl.obolibrary.org/obo/TO_0000387>,
        <http://purl.obolibrary.org/obo/WBPhenotype_0000886>,
        XPO:00000000,
        <http://purl.obolibrary.org/obo/ZP_00000000>,
        WIKIDATA:Q169872,
        WIKIDATA:Q25203551 ;
    linkml:examples "Example(value='MP:0001262', description='decreased body weight')" .
```

~~Also curious - in `biolink-model.owl.ttl`, the majority of the namespaces with properly merged BL cats in kg-phenio are not defined with `@prefix` in the header (e.g., CHEBI, MONDO) so they're still defined with IRIs.~~ The inverse doesn't hold though.

**Comment by caufieldjh** [comment]
Puzzlingly, this is not resolved by https://github.com/monarch-initiative/phenio/pull/21.

**Comment by caufieldjh** [comment]
It would be preferable to solve this in the `phenio.owl` build, or even farther upstream in Biolink itself, but in the interest of Solutions I'll implement a fix for it here in the KG assembly, along with prefix normalization for situations like https://github.com/monarch-initiative/phenio/issues/17.

There may be something happening with KGX's category inference (see https://github.com/biolink/kgx/blob/e2d43f1b80cf0779ca3313f97e73a2ff0d8b2170/kgx/utils/graph_utils.py#L78) causing category membership to be clobbered/ignored.

**Comment by kevinschaper** [comment]
This issue has been focused on node categories, but we noticed that we don't actually have any edge categories yet either. Does that feel similar enough to tack on to this issue, or would it be useful to submit a new one?

**Comment by matentzn** [comment]
> interest of Solutions I'll implement a fix for it here in the KG assembly

Maybe annotating an ontology with BL categories actually belongs in KGX rather than in the upstream ontology.. There should be an option to do so, says my instinct, when you convert an ontology into a graph.

> We don't actually have any edge categories yet either.

Are BL edge labels inferred during the to-kgx process?

**Comment by caufieldjh** [comment]
OK, here's the main issue: KGX happily parses PHENIO's category assignments, it just transforms them to relations without assigning node properties. Example:
```
$ grep ENVO:01001569 merged-kg_edges.tsv
urn:uuid:165861b7-188d-4956-9754-30e8dea04c97   ENVO:01001569   biolink:type    ENVO:01001570           type    Graph
urn:uuid:3f1c190a-8441-4b0a-ab35-fa269014287d   ENVO:01001569   biolink:part_of ENVO:01001571           BFO:0000050     Graph
urn:uuid:30bd0be2-c569-441c-baf1-0d70b7500911   ENVO:01001569   biolink:category        biolink:EnvironmentalFeature            biolink:category        Graph
urn:uuid:f9d9bf6e-8fba-4cf2-b78c-b6aa57d13eb5   ENVO:01001569   biolink:category        biolink:NamedThing              biolink:category        Graph
urn:uuid:b1a4502a-437c-4772-972b-05ed7bb10723   ENVO:01001569   biolink:category        biolink:OntologyClass           biolink:category        Graph

$ grep ENVO:01001569 merged-kg_nodes.tsv
ENVO:01001569   biolink:OntologyClass   Western Australian Mulga Shrublands Ecoregion           Graph
```

Not sure yet why this still works for some other spaces like MONDO but I haven't ruled out KGX doing some potentially conflicting category inference.

**Comment by caufieldjh** [comment]
As for edge categories...I was under the impression we _did_ have those. Are you (@kevinschaper) expecting it to be under `predicate` or under `relation`?
