### ISSUE TITLE
Include semsim in build process

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#78]
See this PR: https://github.com/Knowledge-Graph-Hub/semsim/pull/16

In brief, run `semsim` with each KG-Phenio build.

**Comment by matentzn** [comment]
I now I am beating on it repeatedly but please can we make sure that semsim outputs a standardised format before we introduce it into the various pipelines?

**Comment by caufieldjh** [comment]
@matentzn I hear you! This is a note for future implementation.

**Comment by caufieldjh** [comment]
Closing this - will revisit if it's the preferred option, but current semsim comparisons are more frequently done outside the build process.
