### ISSUE TITLE
Include xrefs

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#79]
KG doesn't contain xrefs but this would be useful for downstream use cases, especially for gene IDs.

**Comment by matentzn** [comment]
I am not so sure about this.. I would possibly prefer to be more deliberate about including mappings using SSSOM? What useful information do you expect to find in xrefs that justifies the extreme noise they have?

**Comment by caufieldjh** [comment]
We get xrefs but we don't really want xrefs, we want nice SSSOM maps. Closing.
