### ISSUE TITLE
Expand node properties

### ISSUE THREAD

**Issue by kevinschaper** [Knowledge-Graph-Hub/kg-phenio#90]
I created this [issue over](https://github.com/monarch-initiative/monarch-ingest/issues/409) in monarch-ingest when I realized that I didn't have synonyms for ontology terms. 

I know that we also need to know if nodes are obsolete, and there's #79 for xrefs.  I have no idea whether to use xrefs as provided or SSSOM mappings in place of them! I wonder the same thing about our gene mapping vs provided xrefs, but this issue has even shown up in the new UI where the interface currently has a spot for both xrefs and equivalent relationships.

**Comment by kevinschaper** [comment]
The synonym & xref columns aren't empty anymore, but I'm not so sure about the quantities. 

For synonym, somehow we're only getting 65 records with the field `synonym` field populated, that's definitely a bug. For xref, we're getting 71k, which isn't as obviously broken, but does seem a bit low.

**Comment by kevinschaper** [comment]
I don't have any sense of xrefs, but given that we probably eventually want to use SSSOM instead, it probably makes more sense to chase after those 274K synonyms

**Comment by matentzn** [comment]
Yes, we should not use xrefs for any reason.

**Comment by caufieldjh** [comment]
I now see xrefs and synonyms populated (in KG build 20241203)
