### ISSUE TITLE
XPO to XPO edges have `infores:unknown`

### ISSUE THREAD

**Issue by caufieldjh** [Knowledge-Graph-Hub/kg-phenio#97]
The transform for adding infores to phenio edges is missing a mapping for XPO, so its edges receive the default value of `infores:unknown`.
This should be `infores:xpo`.

**Comment by caufieldjh** [comment]
@kevinschaper reports that the 20230307 build still appears to have `infores:unknown` for XPO edges.

**Comment by caufieldjh** [comment]
Aha! The issue is that XPO edges come from PHENIO as `OBO:XPO_`, not `XPO:`. They get normalized to the latter, correct prefix after the merge but aren't recognized based on the former prefix.

**Comment by kevinschaper** [comment]
Oooh! Good find!
